### ISSUE TITLE
Install `linter` automatically.

### ISSUE THREAD

**Issue by keplersj** [dschwen/linter-moose#1]
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

**Comment by dschwen** [comment]
This is cool, but will users have to manually install `atom-package-deps` first?

**Comment by keplersj** [comment]
Nope.

**Comment by dschwen** [comment]
Implemented in 45d0b97 and published a v0.4.0.
